#ifndef OS_DISK_KERNEL_H
#define OS_DISK_KERNEL_H

/// Command Register
#define COMMAND_IDENTIFY 0xec
#define COMMAND_IDENTIFY_DMA 0xef

#define COMMAND_READ_LBA28 0x20
#define COMMAND_READ_LBA48 0x24
#define COMMAND_READ_DMA_LBA28 0xc8
#define COMMAND_READ_DMA_LBA48 0x25
#define COMMAND_WRITE_LBA28 0x30
#define COMMAND_WRITE_LBA48 0x34
#define COMMAND_WRITE_DMA_LBA28 0xca
#define COMMAND_WRITE_DMA_LBA48 0x35

#ifdef DISK_SECURITY_COMMAND
#define COMMAND_SECURITY_SET_PASSWORD 0xf1
#define COMMAND_SECURITY_UNLOCK 0xf2
#define COMMAND_SECURITY_FREEZE_LOCK 0xf5
#define COMMAND_SECURITY_DISABLE_PASSWORD 0xf6
#endif

#endif